correct qos param of topo dualtor-aa-56 on th2 platform (#20749)
What is the motivation for this PR?
nightly failure, as below:

KeyError('wm_q_shared_lossless')
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/qos_sai_base.py", line 1767, in dutQosConfig
    qosParams = qpm.run()
  File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/files/brcm/qos_param_generator.py", line 521, in run
    self.prepare_default_parameters()
  File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/files/brcm/qos_param_generator.py", line 640, in prepare_default_parameters
    self.create_default_queue_shared_watermark_parameter(que_profile)
  File "/var/src/sonic-mgmt_vms64-dual-t0-7260-1/tests/qos/files/brcm/qos_param_generator.py", line 580, in create_default_queue_shared_watermark_parameter
    self.qos_params[self.speed_cable_len][que_profile] = self.qos_params[que_profile]
KeyError: 'wm_q_shared_lossless'
ERROR
How did you do it?
add missing qos parameters of topo dualtor-aa-56 for th2 platform.

How did you verify/test it?
pass local test:

Signed-off-by: Yael Tzur <ytzur@nvidia.com>