[action] [PR:23793] [Qos]UpdateFeatureState func call in teardown fixed to run from host (#25321)
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit
easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should
reviewer start? background context?
- List any dependencies that are required for this change.
-->
Correcting the updateFeatureState func call in stopServices teardown
path to run from host ( PR #18884 ),
Summary:
Fixes # (issue)
Failure in multi-dut qos test with error -TypeError: SonicAsic.command()
got an unexpected keyword argument 'module_ignore_errors'
### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
 - [ ] Skipped for non-supported platforms
- [x] Test case improvement


### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [x] 202511

### Approach
#### What is the motivation for this PR?
Failure in multi-dut qos test with error -TypeError: SonicAsic.command()
got an unexpected keyword argument 'module_ignore_errors'
 
#### How did you do it?
the updateFeatureState func call takes the Sonic_host as argument. Hence
corrected the calling function

#### How did you verify/test it?
Executed the qos tests & verified the results
#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

Signed-off-by: ansrajpu <anshu.rajput@nokia.com>
Signed-off-by: mssonicbld <sonicbld@microsoft.com>
Co-authored-by: Anshu <113939367+ansrajpu-git@users.noreply.github.com>