[Python3 migration]Fix test failure in test_sub_port_l2_forwarding.py
Summary:
Fixes #7884 [test_sub_port_l2_forwarding] [test issue] TypeError: a bytes-like object is required, not 'str'

What is the motivation for this PR?
test sub_port_interfaces/test_sub_port_l2_forwarding.py fail over python3 issue:
TypeError: a bytes-like object is required, not 'str'

How did you do it?
In Python3, a string cannot work with bytes
Use str to convert bytes to string

How did you verify/test it?
The change can work both in Python2 and Python3.