Fix init BaseConsoleConn got unexpected param console_device (#17170)
what
[Fix] Fix init BaseConsoleConn got unexpected param console_device

why
The PR(#16686) introduce a param console_device but not remove before BaseConsoleConn passing to parent class.
failure example:

  File "/var/src/sonic-mgmt/tests/common/connections/console_host.py", line 47, in ConsoleHost
    return ConsoleTypeMapper[console_type](**params)
  File "/var/src/sonic-mgmt/tests/common/connections/ssh_console_conn.py", line 35, in __init__
    super(SSHConsoleConn, self).__init__(**kwargs)
  File "/var/src/sonic-mgmt/tests/common/connections/base_console_conn.py", line 51, in __init__
    super(BaseConsoleConn, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'console_device'
how
Remove param console_device before BaseConsoleConn passing to parent class.

test
Verified recover_by_console.py since it used this class, and the script could be executed without init exception.

Signed-off-by: Chun'ang Li <chunangli@microsoft.com>