Fix test_dynamic_acl incompatible issue on dualtor (#17274)
* Fix test_dynamic_acl uncompatible issue on dualtor

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

Description of PR
Summary:
Fixes # (issue)
test_dynamic_acl failed on dualtor testbed due to:

28/02/2025 16:40:42 __init__._fixture_func_decorator         L0073 ERROR  |               
AttributeError("'AnsibleUnsafeText' object has no attribute 'get'")
Traceback (most recent call last):
  File "/data/tests/common/plugins/log_section_start/__init__.py", line 71, in _fixture_func_decorator
    return fixture_func(*args, **kargs)
  File "/data/tests/generic_config_updater/test_dynamic_acl.py", line 227, in setup  
    if config_facts['VLAN_INTERFACE'][vlan_name][vlan_ip_address].get("secondary"):
AttributeError: 'AnsibleUnsafeText' object has no attribute 'get'

It's because the VLAN_INTERFACE is like this on dualtor:

    "VLAN_INTERFACE": {
      "Vlan1000": {
        "grat_arp": "enabled",
        "proxy_arp": "enabled",
        "192.168.0.1/21": {
          
        },
        "fc02:1000::1/64": {
          
        }
      }
    },

Approach
What is the motivation for this PR?
How did you do it?
Avoid to get secondary key from a string object
Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>