Increased MAX fan sped tolerance to 15 percent (#3046)
Description of PR
Summary: Increased tolerance value of MAX acceptable Fan speed in platfom tests.

Approach
What is the motivation for this PR?
From time to time test "test_reload_configuration" can fail with such message:
AssertionError: Invalid fan speed: actual speed=27508, set speed=255, min=1500, max=25000, exception=Fan speed 27508 not in range: [1500, 27500]

As Fan speed is mechanical dependent and different environmental factors can have impact on the fan speed, there can be higher deviation then 10%. So it was decided that 15% tolerance is acceptable for Max Fan speed.

So MAX_FAN_SPEED_THRESHOLD was changed from 10 to 15 % tolerance.

``

How did you verify/test it?
Tested on the local setup.

Signed-off-by: Yuriy Volynets <yuriyv@nvidia.com>