Fix issue 'InterruptableThread' object has no attribute '_e'
The recover_server.py script ocassionally gives error like below:

+ python recover_server.py --testbed-servers server_2 --vm-file veos --vm-type veos --skip-cleanup
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature
INFO - LOG PATH: /tmp/recover_server_2021-09-08_02-52-23
Traceback (most recent call last):
  File "recover_server.py", line 328, in <module>
INFO - Start running task server_2_start_vms
    do_jobs(testbeds, passfile, tbfile=tbfile, vmfile=vmfile, vmtype=vmtype, skip_cleanup=skip_cleanup, dry_run=dry_run)
  File "recover_server.py", line 300, in do_jobs
    _join_all(threads)
  File "recover_server.py", line 238, in _join_all
    alive_thread.join(timeout=0)
  File "/azp/agent/_work/40/s/tests/common/utilities.py", line 160, in join
    if self._e:
AttributeError: 'InterruptableThread' object has no attribute '_e'

The reason is that attribute "_e" is initialized in method "run" of "InterruptableThread". When thread.start() is called,
the run method is scheduled, not executed immediately. If we try to access the "_e" attribute immediate after
thread.start(), there is chance that the "run" method is not executed yet and the "_e" attribute is not available.

The fix is to initialize "_e" attribute in "__init__" method of class "InterruptableThread".

Signed-off-by: Xin Wang <xiwang5@microsoft.com>