[vsonic]: Enhance vSONiC testbed for recovering bgp support (#5677)
#### What is the motivation for this PR?
The testbed may trigger BGP recovering  in the sanity checking stage. But vSONiC cannot support bgp recovering before and the following error would be raised:
```
E               Failed: Processes "['neighbor_vm_recover_bgpd--<SonicHost VM0101>', 'neighbor_vm_recover_bgpd--<SonicHost VM0102>', 'neighbor_vm_recover_bgpd--<SonicHost VM0103>', 'neighbor_vm_recover_bgpd--<SonicHost VM0100>']" failed with exit code "1"
E               Exception:
E               '<class 'tests.common.devices.sonic.SonicHost'>' object has no attribute 'start_bgpd'
E               Traceback:
E               Traceback (most recent call last):
E                 File "/data/sonic-mgmt/tests/common/helpers/parallel.py", line 31, in run
E                   Process.run(self)
E                 File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
E                   self._target(*self._args, **self._kwargs)
E                 File "/data/sonic-mgmt/tests/common/helpers/parallel.py", line 226, in wrapper
E                   target(*args, **kwargs)
E                 File "/data/sonic-mgmt/tests/common/plugins/sanity_check/recover.py", line 129, in neighbor_vm_recover_bgpd
E                   result['start_bgpd'] = nbr_host.start_bgpd()
E                 File "/data/sonic-mgmt/tests/common/devices/base.py", line 50, in __getattr__
E                   "'%s' object has no attribute '%s'" % (self.__class__, module_name)
E               AttributeError: '<class 'tests.common.devices.sonic.SonicHost'>' object has no attribute 'start_bgpd'
```
#### How did you do it?
By leveraging the `vtysh` command to support BGP recovering for vSONiC testbed.

#### How did you verify/test it?
In the vSONiC testbed
1. Shutdown interface by `sudo ifconfig Ethernet1 down`
2. The BGP recovering will be triggered due to sanity check
3. The above exception will not be raised again.

Signed-off-by: Ze Gan <ganze718@gmail.com>