[action] [PR:24866] Fixing `test_vnet_decap` test failure on T0 (#25049)
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit
easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should
reviewer start? background context?
- List any dependencies that are required for this change.
-->
This PR fixes a test failure that happens on T0 topologies for tests in
`test_vnet_decap.py`.

Summary:
Microsoft ADO ID: 37999353
Fixing `test_vnet_decap` test failure on T0.

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
 - [ ] Skipped for non-supported platforms
- [x] Test case improvement


### Back port request
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [x] 202511
- [ ] 202512
- [x] 202605

### Approach
#### What is the motivation for this PR?
This PR enabled `test_vnet_decap.py` to run on T0 topologies: #24446
However, `Ecmp_Utils::select_required_interfaces` assumes that the
device has T1 topology. This results in the following error when the
test is run on a device with T0 topology:
```
Error: failed on setup with "RuntimeError: There are not enough interfaces needed to perform the test. We need atleast 2 interfaces, but only 0 are available."
```
This PR fixes this issue.

#### How did you do it?
Modified `Ecmp_Utils::select_required_interfaces` to accept the topology
of the testbed as a parameter (with the default value of `T1` to ensure
backward compatibility).

#### How did you verify/test it?
Ran the tests on both a T1 and a T0 switch:
```
vxlan/test_vnet_decap.py::test_vnet_decap[inner_ipv4-outer_ipv4] PASSED [ 25%]
vxlan/test_vnet_decap.py::test_vnet_decap[inner_ipv4-outer_ipv6] PASSED [ 50%]
vxlan/test_vnet_decap.py::test_vnet_decap[inner_ipv6-outer_ipv6] PASSED [ 75%]
vxlan/test_vnet_decap.py::test_vnet_decap[inner_ipv6-outer_ipv4] PASSED [100%]
```

#### Any platform specific information?
This test runs only on Cisco-8000 and Mellanox platforms.

#### Supported testbed topology if it's a new test case?
T0 and T1 (and their variations).

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->
N/A

Signed-off-by: Mahdi Ramezani <mramezani@microsoft.com>
Signed-off-by: mssonicbld <sonicbld@microsoft.com>
Co-authored-by: mramezani95 <mramezani@microsoft.com>