Merged PR 3721: [strsvc2]: Add radius passkey config in strsvc2 from PR 2356
[strsvc2]: Add radius passkey config in strsvc2 from PR 2356

Missing config causing test case to fail as below
    duthost.shell("sudo config radius passkey %s" % creds_all_duts[duthost.hostname]['radius_passkey'])
KeyError: 'radius_passkey'

Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>