Fix pdu host unavailable issue (#6271)
Approach
What is the motivation for this PR?
Fix the issue that pdu information is missing on some testbeds:

AttributeError: 'NoneType' object has no attribute 'dut_hostname'
Signed-off-by: Longxiang Lyu lolv@microsoft.com

How did you do it?
For those testbeds without pdu information available, use system request to reboot.

How did you verify/test it?