Fix testbed_vm_info for "tgen" topologies (#4944)
PR https://github.com/Azure/sonic-mgmt/pull/4862 introduced a bug in the testbed_vm_info module.
This caused `testbed-cli.sh deploy-mg` failed for "tgen*" topologies:

```
fatal: [dut-1 -> localhost]: FAILED! => {"changed": false, "msg": "Traceback (most recent call last):\n
    File \"/tmp/ansible_testbed_vm_info_payload_mccbiM/__main__.py\", line 85, in main\n
    neighbor_eos = vm_facts.get_neighbor_eos()\n
    File \"/tmp/ansible_testbed_vm_info_payload_mccbiM/__main__.py\", line 60, in get_neighbor_eos\n
    vm_base = int(self.base_vm[2:])\n
    ValueError: invalid literal for int() with base 10: ''\n"}
```

The reason is that "tgen*" topologies have VM in topology file. For testbeds using "tgen*" topology,
their "vm_base" in testbed.yaml file is empty. Some special handlings are required for testbeds using
"tgen*" topologies. Another fix is to add check for length of "vm_base". Only try to parse start VM
index from "vm_base" only when its length is greater than 2.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>