change topo to multidut-tgen (#14285)
Description of PR
Summary:

Fix two issues:

errors in test_multidut_pfc_pause_lossless_with_snappi.py
snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py::test_pfc_pause_single_lossless_prio[svcstr2-8800-sup-1|4-linecard_configuration_set0-chassis_multi_line_card_multi_asic] 
-------------------------------- live log call ---------------------------------
15:22:32 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/data/sonic-mgmt-int/tests/snappi_tests/multidut/pfc/test_multidut_pfc_pause_lossless_with_snappi.py", line 89, in test_pfc_pause_single_lossless_prio
    run_pfc_test(api=snappi_api,
  File "/data/sonic-mgmt-int/tests/snappi_tests/multidut/pfc/files/multidut_helper.py", line 290, in run_pfc_test
    verify_in_flight_buffer_pkts(duthost=duthost,
  File "/data/sonic-mgmt-int/tests/common/snappi_tests/traffic_generation.py", line 569, in verify_in_flight_buffer_pkts
    pytest_assert(tx_bytes_total < dut_buffer_size,
TypeError: '<' not supported between instances of 'int' and 'NoneType'
wrong topology marker is used in test_multidut_pfcwd_runtime_traffic_with_snappi.py
Type of change
 Bug fix
 Testbed and Framework(new/improvement)
 Test case(new/improvement)
Back port request
 202012
 202205
 202305
 202311
 202405
Approach
What is the motivation for this PR?
Fix test case failure.

How did you do it?
The TypeError was because BUFFER_POOL is not in the default config_db.json for multi-asic platform. need to use config_db[x].json to get it. Use duthost.asic_instance() to suit both pizzabox and multi-asic DUT.
multi-dut test case should use multidut-tgen in the topology marker.
How did you verify/test it?
Verified locally.

co-authorized by: jianquanye@microsoft.com