[action] [PR:23090] Fix interface range shutdown/startup not supported on multi-asic (#25670)
### Description of PR
test_lldp_entry_table_after_all_batched_flap fails on multi-asic
platform.
Error: Interface range not supported in multi-asic platforms !!

The command running at the moment which introduced the error: sudo
config interface -n asic0 shutdown
Ethernet40,Ethernet136,Ethernet104,Ethernet24,Ethernet48,Ethernet120,Ethernet112,Ethernet128,Ethernet0,Ethernet16,Ethernet96,Ethernet72,Ethernet8,Ethernet64,Ethernet32,Ethernet80,Ethernet88,Ethernet56

In multi-asic scenario, port range shutdown/restarted is not supported
by CLI. There's check to prevent this from
sonic-buildimage/src/sonic-utilities/config/main.py
 intf_fs = parse_interface_in_filter(interface_name)
 if len(intf_fs) > 1 and multi_asic.is_multi_asic():
 ctx.fail("Interface range not supported in multi-asic platforms !!")

Solution: Always shutdown/start ports one by one from the list. Then no
need to distinguish if it's multi-asic or not.

### Type of change

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
 - [ ] Skipped for non-supported platforms
- [ ] Test case improvement


### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [X] 202511

### Approach
#### What is the motivation for this PR?
Fix OC test failure
#### How did you do it?

#### How did you verify/test it?
After fix this test passes.

Signed-off-by: wumiao_nokia <wu.miao@nokia.com>
Signed-off-by: mssonicbld <sonicbld@microsoft.com>
Co-authored-by: wumiao_nokia <wu.miao@nokia.com>