[Bug_Fix] Fix cleanup.sh.j2 template doesn't destroy domain properly (#11517)
When I try run the script to clean up domains. will got error:

error: Failed to undefine domain vlab-01
error: Requested operation is not valid: cannot undefine transient domain
That's because the domain was not destroyed properly.