Merged PR 6114: Revert 'use nightly agent to stop bleeding for the consistent failure of migrate_kusto_data'
use nightly agent to stop bleeding for the consistent failure of migrate_kusto_data for now.
nightly agent pool doesn't have the following issue:

```
+ python3 migrate_kusto_data.py
Traceback (most recent call last):
  File "/home/vsts/work/1/s/test_analyzer/migrate_kusto_data.py", line 20, in <module>
    from azure.kusto.ingest import KustoIngestClient
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/__init__.py", line 7, in <module>
    from .ingest_client import QueuedIngestClient
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/ingest_client.py", line 13, in <module>
    from ._resource_manager import _ResourceManager, _ResourceUri
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/_resource_manager.py", line 6, in <module>
    from tenacity import retry_if_exception_type, stop_after_attempt, Retrying, wait_random_exponential
  File "/home/vsts/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsts/work/1/s/test_analyzer/migrate_kusto_data.py", line 22, in <module>
    from azure.kusto.ingest import QueuedIngestClient as KustoIngestClient
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/__init__.py", line 7, in <module>
    from .ingest_client import QueuedIngestClient
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/ingest_client.py", line 13, in <module>
    from ._resource_manager import _ResourceManager, _ResourceUri
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/kusto/ingest/_resource_manager.py", line 6, in <module>
    from tenacity import retry_if_exception_type, stop_after_attempt, Retrying, wait_random_exponential
  File "/home/vsts/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 653, in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio
```

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>

Reverts !6097