Fix test_inner_hashing failure due to config_db change (#7766)
KeyError: 'members' is introduced by this PR sonic-net/sonic-buildimage#13660.
In original config, we use PORTCHANNEL, now it is changed to PORTCHANNEL_MEMBER. So, the relevant test should be updated accordingly.

Test log:
  oports = []
  for ifname in ifnames:
  if po.has_key(ifname):
  oports.append([str(mg_facts['minigraph_ptf_indices'][x]) for x in po[ifname]['members']])
  E KeyError: 'members'

What is the motivation for this PR?
Fix test_inner_harhing issue

How did you do it?
PORTCHANNEL is changed to PORTCHANNEL_MEMBER

How did you verify/test it?
Run test_inner_hashing