Limit core dump size in auto_techsupport (#7131)
Summary: show_techsupport/test_auto_techsupport.py::TestAutoTechSupport::test_max_limit[core] fails with below error:

           AssertionError: New expected techsupport file was not generated
E           assert False
E            +  where False = wait_until(300, 10, 0, is_new_techsupport_file_generated, <MultiAsicSonicHost 7-dut>, [])
On some platforms time needed to generate auto_techsupport dump may take up ~ 15 min or more. Reason for this is that on some platforms, amount of space dedicated to root-overlay could be up to 100 Gb or more, in such case 5 dummy core dumps will be created each with 5% of space, this will resolve in 25 Gb of core dumps.
During auto_techsupport generation, core dumps is copied inside of techsupport dump, and taking in account the size of core dumps, it will take a significant time for this to happen.