fix memory_utilization teardown failure (#18795)
Approach
What is the motivation for this PR?
The memory utilization plugin operates at per test case level, it uses a pytest hook to collect the memory usage before and after each test case.
It then calculates the memory diff and compares it against a predefined threshold, if the difference exceeds the threshold, a pytest failure will be triggered.

Since "@pytest.hookimpl(tryfirst=True)", the hook will execute before all the teardown fixtures.
This means that if the memory check fails, the hook will return failure directly, and cause an exception immediately, interrupting the tear down process, as a result, it will cause the next test case failure with following error message.

AssertionError: previous item was not torn down properly

How did you do it?
Do not raise the failure in hook directly.
Instead, save all the results and report any failures in the test case's teardown fixture to avoid affecting other test cases.

How did you verify/test it?
Run elastic test
https://elastictest.org/scheduler/testplan/684004dba52da0ec6421c4ad?testcase=ecmp%2Ftest_ecmp_sai_value.py&type=console

Signed-off-by: Yael Tzur <ytzur@nvidia.com>