Merged PR 926: Revert 'Add bluefield01 and bluefield02 testbeds'
- Add device and connection info to inventory/graph files
- Create testbed and allocate VMs and PTF IPs
- Modify 'available_vmset_finder' script to account for more topology types

Note: Actual topology file will be created in public repo

Reverts !740

This change caused recover_server failure
```
+ python recover_server.py --testbed-servers server_6 --vm-file veos --vm-type ceos
WARNING - Unsupported testbed type - dpu
Traceback (most recent call last):
  File "recover_server.py", line 330, in <module>
    testbeds = parse_testbed(tbfile, servers)
  File "recover_server.py", line 45, in parse_testbed
    for tbname, tb in testbed.TestbedInfo(testbedfile).testbed_topo.items():
  File "/azp/agent/_work/49/s/tests/common/testbed.py", line 61, in __init__
    self.parse_topo()
  File "/azp/agent/_work/49/s/tests/common/testbed.py", line 369, in parse_topo
    with open(topo_file, 'r') as fh:
IOError: [Errno 2] No such file or directory: '/azp/agent/_work/49/s/tests/common/../../ansible/vars/topo_dpu.yml'
```