[apiserver] Replace dot-notation with brackets for dict variables (#3572)
Signed-off-by: Neetha John <nejo@microsoft.com>

API server deployment was failing with the following error
TASK [vm_set : Pull and start Keysight API Server container] ***********************************************************************************************
task path: /var/nejo/Networking-acs-sonic-mgmt/ansible/roles/vm_set/tasks/add_topo.yml:55
Tuesday 25 May 2021 18:07:29 +0000 (0:00:00.039) 0:01:05.763 ***********
fatal: [STR2-ACS-SERV-20]: FAILED! => {
"msg": "The field 'remote_user' has an invalid value, which includes an undefined variable. The error was: 'dict object' has no attribute 'vm_host'"
}

How did you do it?
Use brackets to access dictionary variables instead of dot notation

How did you verify/test it?
Ran add-topo successfully with the change