Update test_crm.py
2023-12-03T20:03:09.7943215Z tests/crm/test_crm.py:28:1: F811 redefinition of unused 'CRM_UPDATE_TIME' from line 15
2023-12-03T20:03:09.7944672Z tests/crm/test_crm.py:1202:96: E502 the backslash is redundant between brackets
2023-12-03T20:03:09.7946249Z tests/crm/test_crm.py:1203:9: E128 continuation line under-indented for visual indent