Revert "Enhance qos tests to support single-asic, multi-asic, and multi-dut testing (#8213)" (#8252)
This reverts commit 7120af94ce3ffaade6235155259c629ab4900dee.

Summary:
Fixes many internal QoS test failures caused by #8213
Such as:
File "/azp/_work/26/s/tests/qos/test_pfc_counters.py", line 96, in run_test
peer_port_name = eos_to_linux_intf(peer_port)
File "/azp/_work/26/s/tests/qos/qos_helpers.py", line 38, in eos_to_linux_intf
elif "Nokia" in hwsku:
TypeError: argument of type 'NoneType' is not iterable

How did you do it?
Revert #8213

How did you verify/test it?
N/A