Fixing the limited_ports argument not found error in platform_tests/sfp/test_sfputils.py (#25890)
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit
easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should
reviewer start? background context?
- List any dependencies that are required for this change.
-->

Summary:
When we run the platform_tests, we run into this problem from
platform_tests/sfp/test_sfputils.py:
```
e="platform_tests/sfp/test_sfputil.py" line="480" time="37.240"><properties><property name="start" value="2026-06-19 06:03:48.908808" /><property name="end" value="2026-06-19 06:04:26.340743" /></properties><error
 message="failed on setup with &quot;ValueError: no option named 'limited_ports'&quot;">self = &lt;_pytest.config.Config object at 0x73829bc8b8b0&gt;, name = 'limited_ports', default = &lt;NOTSET&gt;, skip = False

    def getoption(self, name: str, default=notset, skip: bool = False):
        """Return command line option value.
    
        :param name: Name of the option.  You may also specify
            the literal ``--OPT`` option instead of the "dest" option name.
        :param default: Default value if no option of that name exists.
        :param skip: If True, raise pytest.skip if option does not exists
            or has a None value.
        """
        name = self._opt2dest.get(name, name)
        try:
&gt;           val = getattr(self.option, name)
E           AttributeError: 'Namespace' object has no attribute 'limited_ports'

default    = &lt;NOTSET&gt;
name       = 'limited_ports'
self       = &lt;_pytest.config.Config object at 0x73829bc8b8b0&gt;
skip       = False

/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1611: AttributeError

The above exception was the direct cause of the following exception:

args = (&lt;SubRequest 'limited_ports' for &lt;Function test_check_sfputil_reset[tb3-c0-dut1-None]&gt;&gt;,), kw = {}

    def fun(*args, **kw):
        if not kwsyntax:
            args, kw = fix(args, kw, sig)
&gt;       return caller(func, *(extras + args), **kw)

args       = (&lt;SubRequest 'limited_ports' for &lt;Function test_check_sfputil_reset[tb3-c0-dut1-None]&gt;&gt;,)
caller     = &lt;function _pytest_import_callback.&lt;locals&gt;._fixture_func_decorator at 0x7382969f4310&gt;
extras     = ()
func       = &lt;function limited_ports at 0x73829645a940&gt;
kw         = {}
kwsyntax   = False
sig        = &lt;Signature (request)&gt;

/usr/local/lib/python3.8/dist-packages/decorator.py:235: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common/plugins/log_section_start/__init__.py:71: in _fixture_func_decorator
    return fixture_func(*args, **kargs)
        args       = (&lt;SubRequest 'limited_ports' for &lt;Function test_check_sfputil_reset[tb3-c0-dut1-None]&gt;&gt;,)
        fixture_func = &lt;function limited_ports at 0x73829645a940&gt;
        kargs      = {}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

request = &lt;SubRequest 'limited_ports' for &lt;Function test_check_sfputil_reset[tb3-c0-dut1-None]&gt;&gt;

    @pytest.fixture(scope="module")
    def limited_ports(request):
&gt;       return request.config.getoption('--limited_ports')
E       ValueError: no option named 'limited_ports'

request    = &lt;SubRequest 'limited_ports' for &lt;Function test_check_sfputil_reset[tb3-c0-dut1-None]&gt;&gt;

```

We don't see the problem when the test_sfputils.py is run alone. This PR
attempts to fix this.

<!--
If you request a backport/cherry-pick below, link the GitHub issue or
ADO work
item here (for example, "Fixes #<issue>" or "ADO: <work item URL>").
-->

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement


### Back port request
<!--
Only check a release or feature branch when the PR links a GitHub issue
or ADO
work item above. The linked tracker should explain the failure in
detail,
including whether it is a day-one issue or a regression, the affected
branch/image/platform/test, and why this branch needs the fix. Backport
or
cherry-pick requests without a linked issue/work item may not be
favored.
-->
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [X] 202511
- [X] 202512
- [X] 202605
- [X] 202603
- [X] 202601

Tracking issue/work item for backport/cherry-pick request:
Failure type: <!-- other -->

### Approach
#### What is the motivation for this PR?
Fixing the error from test_sfputils.py.

#### How did you do it?
Moved the pytest_addoption to the platform_tests/conftest.py instead of
current platform_tests/sfp/conftest.py.

#### How did you verify/test it?
Ran it on my testbed. It is passing when platform folder is run.

---------

Signed-off-by: Raghavendran Ramanathan <rraghav@cisco.com>