argparse conflicting option string (#18348) (#21419)
Two option strings, `--num_routes` and `--skip_cleanup` conflict between
a couple of test suites.  This causes `./run_tests.sh` when executing test
cases simultaneously (such as when running the full suite) to exit with
an error of something like:
```
argparse.ArgumentError: argument --num_routes: conflicting option string(s): --num_routes
```

Move these arguments into the global scope from their conflicting
locations.

This fixes upstream issue https://github.com/sonic-net/sonic-mgmt/issues/5526

Signed-off-by: Brad House <bhouse@nexthop.ai>
Co-authored-by: Brad House - NextHop <bhouse@nexthop.ai>
Co-authored-by: Brad House <brad@brad-house.com>