Update test_arp.py
Clearing ARP Table , so we VLAN Interface entry can be cleared from ARP Table.

Also, Line 125, waitapi.arp_clear_on_link_down(vars.D1T1P1), through below error.
ERROR Exception: AttributeError 'module' object has no attribute 'arp_clear_on_link_down'