[Vrf] Update check of REDIRECT_ACTION and acl_redirect rule (#5726)
Test cases in TestVrfAclRedirect fail with below error:
```
FAILED vrf/test_vrf.py::TestVrfAclRedirect::test_origin_ports_recv_no_pkts_v4 - Exception
"AssertionError: Received packet that we expected not to receive on device 0, port 28."

FAILED vrf/test_vrf.py::TestVrfAclRedirect::test_origin_ports_recv_no_pkts_v6 - Exception
"AssertionError: Received packet that we expected not to receive on device 0, port 28."

FAILED vrf/test_vrf.py::TestVrfAclRedirect::test_redirect_to_new_ports_v4 - Exception
"AssertionError: Received expected packet on port 28 for device 0, but it should have arrived on one of these ports: [29, 31]."

FAILED vrf/test_vrf.py::TestVrfAclRedirect::test_redirect_to_new_ports_v6 - Exception
"AssertionError: Received expected packet on port 28 for device 0, but it should have arrived on one of these ports: [29, 31]."
Made below changes that fix test cases:
```

Run TC if REDIRECT_ACTION is present in 'ACL_STAGE_CAPABILITY_TABLE|INGRESS', otherwise skip TC as for redirect is not supported.

Updated vrf_acl_redirect.j2 rule for vrf/test_vrf.py::TestVrfAclRedirect, due to changes made in ptftests/fib_test.py where src_ip was changed.

Signed-off-by: Andrii-Yosafat Lozovyi <andrii-yosafatx.lozovyi@intel.com>