[common - config_reload] Add workaround for 202012 tests to pass (#16741)
What is the motivation for this PR?
Some test cases fail due to passing keyword arguments to this function which don't exist in this branch (as it is old and relatively inactive, it does not receive the most up-to-date cherry picks). Resolving these differences would be quite time consuming and error-prone, as this branch has diverged quite significantly from the master branch.

How did you do it?
Added **kwargs to the config_reload function signature, along with warning logs printing any unhandled keyword arguments (to assist in debugging, in the event that these arguments are required for passing results).

How did you verify/test it?
Previously, running cacl/test_cacl_application.py::test_cacl_acl_loader_commands_internal threw the following exception:

08:30:07 __init__._fixture_generator_decorator    L0089 ERROR  |
TypeError("config_reload() got an unexpected keyword argument 'check_intf_up_ports'",)
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_tbtk5-t0-dx010-4_65a9f3c1abd5cba890cf2075/tests/common/plugins/log_section_start/__init__.py", line 85, in _fixture_generator_decorator
    next(it)
  File "/var/src/sonic-mgmt_tbtk5-t0-dx010-4_65a9f3c1abd5cba890cf2075/tests/cacl/test_cacl_application.py", line 190, in setup_acl_tables
    config_reload(duthost, safe_reload=True, check_intf_up_ports=True)
  File "/var/src/sonic-mgmt_tbtk5-t0-dx010-4_65a9f3c1abd5cba890cf2075/tests/common/plugins/loganalyzer/utils.py", line 24, in decorated
    res = func(*args, **kwargs)
TypeError: config_reload() got an unexpected keyword argument 'check_intf_up_ports'
After these changes, we are able to run the testcase successfully:
image
Additionally, warning logs are thrown containing information about any unused kwargs:
image

Any platform specific information?
N/A

Supported testbed topology if it's a new test case?
N/A