Fix `tests/snappi_tests/qos/files/packet_reorder_helper.py` failures (#18948)
Description of PR
Summary: Fix tests/snappi_tests/qos/files/packet_reorder_helper.py test failures
Fixes # #18947

Type of change
 Bug fix
 Testbed and Framework(new/improvement)
 New Test case
 Skipped for non-supported platforms
 Test case improvement
Back port request
 202205
 202305
 202311
 202405
 202411
 202505
Approach
What is the motivation for this PR?
Issue 1#
Test is setting packet increment count property to "100000" (See TOTAL_NUM_PKTS in qos/files/packet_reorder_helper.py) in the snappi config but snappi api expects this property value to be less than or equal to "65535" as part of types validation of the config. And thus causing test to fail with SnappiIxnException exception. See class PatternFlowIpv4IdentificationCounter and _validate_types method in https://github.com/open-traffic-generator/snappi/blob/main/snappi/snappi.py.

Issue 2#
After fixing above issue, test fails with FAILED snappi_tests/qos/test_ipip_packet_reorder_with_snappi.py::test_ip_in_ip_packet_reorder[ld114|0] - AttributeError: 'Api' object has no attribute 'transmit_state'

How did you do it?
For Issue 1#, updated test to use lesser number (set to 50000)
For Issue 2# made changes similar to #18897

How did you verify/test it?
With above two fixes, test is passing consistently.

Any platform specific information?
Supported testbed topology if it's a new test case?

signed-off-by: jianquanye@microsoft.com