Revert "[fwutil] Fix Various Bugs Identified in Regression (#5130)" (#5312)
Reverts #5130

Need to revert this PR for the same reason as PR #5282.

The dependent pytest-allure package which is only available to user “AzDevOps” in sonic-mgmt docker because it is installed to local path of that user:
```
AzDevOps@2fb15ed04ed5:~$ python
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import allure
>>> allure.__file__
'/var/AzDevOps/.local/lib/python2.7/site-packages/allure.pyc'
AzDevOps@2fb15ed04ed5:~$ sudo su
root@2fb15ed04ed5:/var/AzDevOps# pip list | grep allure
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
root@2fb15ed04ed5:/var/AzDevOps# python
Python 2.7.17 (default, Feb 27 2021, 15:10:58)
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import allure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named allure
>>> exit()
```
I’ll revert this PR for now to unblock testing using root account. The sonic-mgmt docker file https://github.com/Azure/sonic-buildimage/blob/master/dockers/docker-sonic-mgmt/Dockerfile.j2 needs to be updated to ensure that package pytest-allure is installed to global directory.