Modified CONTAINER_NAME_REGEX to match mgmt-framework #4466 (#4538)
test_container_autorestart failed the test for mgmt-framework container since CONTAINER_NAME_REGEX does not match mgmt-framework

What is the motivation for this PR?
test_container_autorestart failed the test for mgmt-framework container since CONTAINER_NAME_REGEX does not match mgmt-framework

    ],
        'swss' : swss_syncd_teamd_regex,
        'syncd' : swss_syncd_teamd_regex,
        'teamd' : swss_syncd_teamd_regex,
    }

    _, container_name = decode_dut_port_name(enum_dut_feature_container)
  feature = re.match(CONTAINER_NAME_REGEX, container_name).group(1)

E AttributeError: 'NoneType' object has no attribute 'group'

_ = 'mathilda-4'
container_name = 'mgmt-framework'
duthost = mathilda-4
enum_dut_feature_container = 'mathilda-4|mgmt-framework'
ignore_regex_dict = {'common': ['.ERR monit.', '.ERR systemd.Failed to start . container', '.ERR kernel.PortChannel.', '.ERR rou...ute_enum_values_capability.', '.ERR syncd[0-9]#syncd.SAI_API_SWITCH:sai_object_type_get_availability.', ...], ...}
loganalyzer = None
swss_syncd_teamd_regex = ['.ERR swss[0-9]#orchagent.removeLag.', '.ERR syncd[0-9]#syncd.driverEgressMemoryUpdate.', '.ERR syncd[0-9]#...attribute_enum_values_capability.', '.ERR syncd[0-9]#syncd.SAI_API_SWITCH:sai_object_type_get_availability.', ...]

autorestart/test_container_autorestart.py:99: AttributeError

* generated xml file: /data/tests/run_logs_DT15_1/autorestart/test_container_autorestart_2021-09-02-02-07-11.xml -
INFO:root:Can not get Allure report URL. Please check logs
---------------------------- live log sessionfinish ----------------------------
02:37:28 init.pytest_terminal_summary L0064 INFO | Can not get Allure report URL. Please check logs
=========================== short test summary info ============================
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container sflow
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container nat
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container database
ERROR autorestart/test_container_autorestart.py::test_containers_autorestart[mathilda-4-mathilda-4|mgmt-framework]
=============== 10 passed, 3 skipped, 1 error in 1816.51 seconds ===============

How did you do it?
Changed CONTAINER_NAME_REGEX = (r"([a-zA-Z_]+)(\d*)$") to CONTAINER_NAME_REGEX = (r"([a-zA-Z_-]+)(\d*)$") to match the container name "mgmt-framework"

How did you verify/test it?
Implemented the changes and ran the autorestart/test_container_autorestart.py script, script able to identify the mgmt-framework container and test passed
=========================================================== short test summary info ============================================================
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container sflow
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container radv
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container nat
SKIPPED [1] /data/tests/common/helpers/assertions.py:13: Skipping test for container database
=================================================== 10 passed, 4 skipped in 1537.57 seconds ====================================================