Merged PR 4258: Fix no "utcnow" attribute issue of reduce_and_add_sonic_images (#11114)
Fix no "utcnow" attribute issue of reduce_and_add_sonic_images

Recent PR #10856 improved debugability of the customzied ansible
module reduce_and_add_sonic_images.
However, this module ran into issue below issue on 202205 branch:

    AttributeError(\"module 'datetime' has no attribute 'utcnow'\")

The reason is related with the notorious datetime.datetime issue.
Packate datetime has module with same name datetime. If some module
imported the datetime package using:
    import datetime

Then below statement for importing the datetime module may be skipped
because in imported cache, there is already "datetime".
    from datetime import datetime

Consequently, `datetime.utcnow()` may fail with AttributeError.

To avoid the mess of such issue, this PR updated the module to use the
`time` module to generate timestamp.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>