Merged PR 3682: [mx][dhcp_server] Fix chaddr convert error due to python version
This test case would fail in python3 like below:
```
14:48:04 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1761, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 192, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/src/sonic-mgmt_testbed-bjw-can-720dt-2_646f1406735219c3e5444108/tests/mx/test_dhcp_server.py", line 380, in test_dhcp_server_tc3_packet
    dhcp_packet_test(duthost, enum_asic_index, vlan_config, ptfadapter, verify_bmc_map)
  File "/var/src/sonic-mgmt_testbed-bjw-can-720dt-2_646f1406735219c3e5444108/tests/mx/test_dhcp_server.py", line 327, in dhcp_packet_test
    dhcp_discover_pkt = create_dhcp_discover_request_packet(request_param_list, eth_client=ptf_port_mac,
  File "/var/src/sonic-mgmt_testbed-bjw-can-720dt-2_646f1406735219c3e5444108/tests/mx/test_dhcp_server.py", line 291, in create_dhcp_discover_request_packet
    chaddr=testutils.__dhcp_mac_to_chaddr(eth_client),
  File "/usr/local/lib/python3.8/dist-packages/ptf/testutils.py", line 2722, in __dhcp_mac_to_chaddr
    chaddr = "".join([chr(int(octet, 16)) for octet in mac_addr.split(":")])
TypeError: a bytes-like object is required, not 'str'
```

Add support for dhcp_mac_to_chaddr in python3