fix PR#8557 and PR#8377 (#8644)
What is the motivation for this PR?
encounter qos test, caused by below 2 bad fixs:

bad fix from PR #8557

  File "/home/xuchen3/env-d/sonic-mgmt-int/tests/qos/test_qos_sai.py", line 765, in testQosSaiSharedReservationSize
    (src_port_ids, dst_portids) = check_skip_shared_res_test
ValueError: too many values to unpack
bad fix from PR#8377

>           "dst_port_ids": dst_port_ids,
            "dst_port_ips": [dst_testPortIps[port]['peer_addr'] for port in dst_port_ids],
            "pkt_counts":  qosConfig[sharedResSizeKey]["pkt_counts"],
            "shared_limit_bytes": qosConfig[sharedResSizeKey]["shared_limit_bytes"],
            "hwsku":dutTestParams['hwsku']
        })
E       NameError: global name 'dst_port_ids' is not defined

How did you do it?
resolve bad fix