[202012] Cherry-pick dut_ports.py for 202012 (#7369)
What is the motivation for this PR?
PR #6074 was not merged to 202012, but most of its code have been merged into 202012 within #6055.
But the function get_duthost_with_name in dut_ports.py is missed and test case failed with below error:

___________________ ERROR collecting tests/pc/test_lag_2.py ____________________
ImportError while importing test module '/azp/_work/37/s/sonic-mgmt-int/tests/pc/test_lag_2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
pc/test_lag_2.py:14: in <module>
    from tests.common.helpers.dut_ports import get_duthost_with_name
E   ImportError: cannot import name get_duthost_with_name

How did you do it?
Add this function for 202012 in this PR.

How did you verify/test it?
Run pc/test_lag_2.py against 202012 branch.

Signed-off-by: Zhaohui Sun <zhaohuisun@microsoft.com>