[Platform API] HTTP server handles NotImplementedError (#1822)
Previously, if the HTTP server attempted to execute a non-implemented API, the API would throw `NotImplementedError`, but the HTTP server did not handle this exception, thus it would not send a proper HTTP response, causing the pytests to fail with `BadStatusLine`. Example:

```
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_name - BadStatusLine: ''
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_model - BadStatusLine: ''
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_serial - BadStatusLine: ''
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_status - BadStatusLine: ''
```

With this change, the HTTP server handles the exception and now sends a proper HTTP response containing `None`, which allows the pytests to interpret the failure properly. Example:

```
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_name - Failed: Unable to retrieve transceiver 0 name
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_model - Failed: Unable to retrieve transceiver 0 model
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_serial - Failed: Unable to retrieve transceiver 0 model
FAILED platform_tests/api/test_sfp.py::TestSfpApi::test_get_status - Failed: Unable to retrieve transceiver 0 status
```

The server will now also log a warning on the DuT.