Added fix for getting of num_asics in TestbedProcessing (#4319)
Added fix for getting of num_asics in TestbedProcessing

What is the motivation for this PR?
Changes from 3746 cause a minor issue in TestbedProcessing.py module. If num_asics value is None, makeLab function will fails due to TypeError.

Traceback (most recent call last):
  File "TestbedProcessing.py", line 857, in <module>
    main()
  File "TestbedProcessing.py", line 842, in main
    makeLab(device_groups, devices, testbed, args.basedir + lab_file)  # Generate lab in INI file format (LAB)
  File "TestbedProcessing.py", line 460, in makeLab
    num_asics = int(dev.get("num_asics"))
TypeError: int() argument must be a string or a number, not 'NoneType'

How did you do it?
Move converting of num_asics to if block.

Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>