Check CRM limit for route performance limit test (#2461)
Fixing the failure of test_route_perf in S6100 platforms
The test adds the ipv4 and ipv6 routes based on the input arg --num_routes (default 10000 routes)
It fails where the available limit is less than the number of routes being added.
Error: failed to execute api: create, key: SAI_OBJECT_TYPE_ROUTE_ENTRY, status: SAI_STATUS_TABLE_FULL

Fix: Added a check for setting the route addition limit based on CRM resource availability.