Merged PR 2386: Exclude public graph files from graph_files.yaml list
Exclude public graph files from graph_files.yaml list

There is a corner issue of checking pdu_status for str-msn2700-01:
```
xiwang5@cda3b8c3a731:~/code/sonic-mgmt/ansible$ ./devutils -l str-msn2700-01 -i str -a pdu_status --log-level debug
DEBUG:root:Looking at conn graph file: lab_connection_graph.xml for hosts [u'str-msn2700-01']

...

DEBUG:root:Returning lab graph from conn graph file: lab_connection_graph.xml for hosts [u'str-msn2700-01']
DEBUG:root:For str-msn2700-01 with hwsku Mellanox-2700, port_name_list is ['Ethernet0', 'Ethernet4', 'Ethernet8', 'Ethernet12', 'Ethernet16', 'Ethernet20', 'Ethernet24', 'Ethernet28', 'Ethernet32', 'Ethernet36', 'Ethernet40', 'Ethernet44', 'Ethernet48', 'Ethernet52', 'Ethernet56', 'Ethernet60', 'Ethernet64', 'Ethernet68', 'Ethernet72', 'Ethernet76', 'Ethernet80', 'Ethernet84', 'Ethernet88', 'Ethernet92', 'Ethernet96', 'Ethernet100', 'Ethernet104', 'Ethernet108', 'Ethernet112', 'Ethernet116', 'Ethernet120', 'Ethernet124']
Traceback (most recent call last):
  File "./devutils", line 426, in <module>
    main()
  File "./devutils", line 422, in main
    action_dispatcher(parameters)
  File "./devutils", line 313, in action_dispatcher
    parameters['action'](parameters)
  File "./devutils", line 269, in action_pdu_status
    header, data = action_pdu(parameters, 'status')
  File "./devutils", line 263, in action_pdu
    data.append([status[x] for x in header])
TypeError: string indices must be integers, not str
```

The reason is that conn_graph_facts module supports find out graph xml file based on supplied hostname.
However, the sample connection graph xml file lab_connection_graph.xml also has "str-msn2700-01".
Consequently, a wrong connection graph xml file is used by devutils and triggered this issue.

The fix is to remove the public graph xml files from the list in graph_files.yaml file.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>