Fix snappi_tests/test_snappi.py (#18897)
Description of PR
Summary: Fix snappi_tests/test_snappi.py failure
Fixes # #18896

Type of change
 Bug fix
 Testbed and Framework(new/improvement)
 New Test case
 Skipped for non-supported platforms
 Test case improvement

Approach
What is the motivation for this PR?
Test is failing with

============================================================================================== short test summary info ===============================================================================================
FAILED snappi_tests/test_snappi.py::test_snappi - AttributeError: 'Api' object has no attribute 'transmit_state'
====================================================================================== 1 failed, 1 warning in 595.57s (0:09:55) ==================================================================
How did you do it?
Updating test to adopt to newer version of snappi introduced by sonic-net/sonic-buildimage#22345 and fix is similar to #18523

How did you verify/test it?
Test is passing with the test.