[cacl]Run cacl test case on one dut per hwsku (#7617) (#7671)
What is the motivation for this PR?
Failure seen on test_cacl_function when run on Chasiss Supervisor, works fine on Linecard.
This is because the Supervisor does not have SNMP/SSH ACL table, so when the ACLs are loaded in the test case, they don't take effect and ssh to Sup does not stop.
Test fails with error:
Failed: SSH port did not stop. Timeout when waiting for <ip> to stop.
Failure seen on test_ebtables_application when run on Chassis testbed with different HwSKU with different number of asics.
The test case uses rand_one_dut_hostname and enum_asic_index.
The rand_one_dut_hostname selects a random dut of the testbed but enum_asic_index is generated based on the first DUT of the testbed. This causes a mismatch between the dut that is selected and asic_index. This causes test case to fail with below error:
expected_ebtables_rules = generate_expected_rules(duthost)
>       stdout = duthost.asic_instance(enum_asic_index).command("sudo ebtables -L FORWARD")["stdout"]
E       AttributeError: 'NoneType' object has no attribute 'command'
How did you do it?
For error 1, add SNMP/SSH/NTP acl table in Supervisor minigraph.
Update test_cacl_function to run on one dut per hwsku so that it runs on sup and required linecards.
For error 2, update test_ebtables test to run one dut per hwsku so that it runs on sup and required linecards.

How did you verify/test it?
Both tests are passing on Chassis testbed.
Before minigraph change:
sup-1:/etc/sonic$ show acl table
Name    Type    Binding    Description    Stage
------  ------  ---------  -------------  -------
After minigraph change:
sup-1:/etc/sonic$ show acl table
Name      Type       Binding    Description    Stage
--------  ---------  ---------  -------------  -------
NTP_ACL   CTRLPLANE  NTP        NTP_ACL        ingress
SNMP_ACL  CTRLPLANE  SNMP       SNMP_ACL       ingress
SSH_ONLY  CTRLPLANE  SSH        SSH_ONLY       ingress

(cherry picked from commit 1eb048bb3f3193233950973e5db756cfc1459dbb)