Fix _strptime issue (#9644)
When running warm-reboot or fast-reboot test, sometimes we can encounter the error:[Functional] [fast-reboot] | Exception occurred when parsing logs from VM: msg='module' object has no attribute '_strptime' type=<type 'exceptions.AttributeError'>.

This issue is a python2.7 known issue(https://stackoverflow.com/a/22476843/2514803), and it was fixed in sonic-mgmt before. But the relevant fix was removed by mistake by the PR: https://github.com/sonic-net/sonic-mgmt/pull/7968/files. However, the relevant fix still exists on the branch 202205 and before. So, add it back.