[everflow]fix issue: missing mirror_stage in testcase_6 (#1381)
Fixes the following issue

```
TASK [test : debug] ************************************************************ 
task path: /root/mars/workspace/sonic-mgmt/ansible/roles/test/tasks/ptf_runner.yml:52 
Wednesday 12 February 2020  17:08:08 +0000 (0:00:02.544)       0:14:55.685 **** 
ok: [arc-switch1004-t1-lag] => { 
    "out.stdout_lines": [ 
        "everflow_neighbor_test.EverflowNeighborTest ... ERROR", 
        "", 
"======================================================================", 
        "ERROR: everflow_neighbor_test.EverflowNeighborTest", 
        "----------------------------------------------------------------------", 
        "Traceback (most recent call last):", 
        "  File \"acstests/everflow_neighbor_test.py\", line 194, in runTest", 
        "    self.check_mirrored_packet()", 
        "  File \"acstests/everflow_neighbor_test.py\", line 137, in check_mirrored_packet", 
        "    if self.mirror_stage == \"egress\":", 
        "AttributeError: 'EverflowNeighborTest' object has no attribute 'mirror_stage'", 
        "", 
        "----------------------------------------------------------------------", 
        "Ran 1 test in 0.004s", 
        "", 
        "FAILED (errors=1)" 
    ] 
} 
Read vars_file 'vars/docker_registry.yml' 
```