Merged PR 10076: [Fix] Fix init BaseConsoleConn got unexpected param console_device
**what**
[Fix] Fix init BaseConsoleConn got unexpected param console_device
Same github PR: https://github.com/sonic-net/sonic-mgmt/pull/17170

**why**
The PR(https://github.com/sonic-net/sonic-mgmt/pull/16686) introduce a param `console_device` but not remove before passing to parent class.
failure example: https://elastictest.org/scheduler/testplan/67bd07e96a17321fa3ea6be9?testcase=testbed_q_star_lab_vms11-t1-4700-6_prepare.log&type=prepare
```
  File "/var/src/sonic-mgmt_vms11-t1-4700-6_6670b1f1e72b94cbabbdfe65/tests/common/connections/console_host.py", line 47, in ConsoleHost
    return ConsoleTypeMapper[console_type](**params)
  File "/var/src/sonic-mgmt_vms11-t1-4700-6_6670b1f1e72b94cbabbdfe65/tests/common/connections/ssh_console_conn.py", line 35, in __init__
    super(SSHConsoleConn, self).__init__(**kwargs)
  File "/var/src/sonic-mgmt_vms11-t1-4700-6_6670b1f1e72b94cbabbdfe65/tests/common/connections/base_console_conn.py", line 51, in __init__
    super(BaseConsoleConn, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'console_device'
```

**how**
Remove param `console_device` before passing to parent class.

**test**
Verified `recover_by_console.py` since it used this class, and the script could be executed without init exception.

----
#### AI description  (iteration 1)
#### PR Classification
Bug fix

#### PR Summary
Fixes an issue where `BaseConsoleConn` received an unexpected parameter `console_device`.
- `tests/common/connections/base_console_conn.py`: Added `console_device` to the list of keys to be removed from `kwargs`.
<!-- GitOpsUserAgent=GitOps.Apps.Server.pullrequestcopilot -->