Merged PR 3222: [double commit][internal] fix str3-8101-01 fanout port alias
double commit: [PR #3183](https://dev.azure.com/mssonic/internal/_git/sonic-mgmt-int/pullrequest/3183)

fix str3-8101-01 fanout port alias

partial revert PR3072
to correct str3-8101-01 fanout port alias.

## motivation:
observed portchannle related testcase failure:
```
{"changed": true, "cmd": ["sudo", "config", "interface", "startup", "etp22b"], "delta": "0:00:00.827058",
"end": "2023-07-14 10:51:13.321946",
"failed": true, "msg": "non-zero return code",
"rc": 2, "start": "2023-07-14 10:51:12.494888",
"stderr": "Usage: config interface startup [OPTIONS] <interface_name>
Try \"config interface startup -h\" for help.

Error: Interface name is invalid. Please enter a valid interface name!!",
"stderr_lines": ["Usage: config interface startup [OPTIONS] <interface_name>",
"Try \"config interface startup -h\" for help.",
"",
"Error: Interface name is invalid. Please enter a valid interface name!!"], "stdout": "",
"stdout_lines": [], "warnings": ["Consider using 'become', 'become_method', and 'become_user' rather than running sudo"]}
```
## RCA:
For sonic fanout switch, not support interface config command using alias "ethXXX", need to change alias to "EthernetXXX".

## trade-off:
because revert PR3072,
fanout switch deploy failure is expected, to resovle fanout deploy failure, can manually change alias name to "etpXXX".