Merged PR 209: Update platform info for 7050qx-32s
Update platform info for 7050qx-32s

Signed-off-by: Neetha John <nejo@microsoft.com>

Test results on backend T1

================================================================================ short test summary info =================================================================================
SKIPPED [1] /var/nejo/sonic-mgmt-int/tests/platform_tests/api/test_chassis.py:484: skipped as this test is applicable to modular chassis only
SKIPPED [1] /var/nejo/sonic-mgmt-int/tests/platform_tests/api/test_chassis.py:491: skipped as this test is applicable to modular chassis only
SKIPPED [1] /var/nejo/sonic-mgmt-int/tests/common/utilities.py:37: DUT has version 20201231.34 and test does not support 201811, 201911, 202012
FAILED platform_tests/api/test_chassis.py::TestChassisApi::test_sfps[str2-7050qx-32s-acs-03] - Failed: SFP number 4 object is incorrect index 6, SFP number 5 object is incorrect index...
==================================================================== 1 failed, 20 passed, 3 skipped in 274.15 seconds ====================================================================