Filter and ignore non-ascii characters in the test pattern
Although PR https://github.com/Azure/sonic-mgmt/pull/3690/ is merged,
the test case test_show_platform_psustatus still failed due to non-ascii
char in the test pattern.

Filter and ignore this non-ascii chars in the test pattern.

See the output of "show platform psustatus",
there may be non-ascii chars in the Model name of some PSUs.

Test error log:
pytest_assert(psu_match, "Unexpected PSU status output: '{}' on '{}'".format(line, duthost.hostname))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xcb' in position 15: ordinal not in range(128)