Update test_ro_disk.py (#14150)
Improve test_ro_disk logrotate failed because auth.log missing issue.

#### Why I did it
test case  test_ro_disk failed because following error:
error: stat of /var/log/syslog failed: Bad message
du: cannot access '/var/log/auth.log': Bad message

### How I did it
Improve test_ro_disk logrotate failed because auth.log missing issue.

#### How to verify it
Pass all test case.

### Description for the changelog
Improve test_ro_disk logrotate failed because auth.log missing issue.

Signed-off-by: yenlu <yenlu@cisco.com>