Fix issue due to TypeError: 'dict_keys' object is not subscriptable (#11330)
Fixes below BT:

decap/test_decap.py::test_decap[ttl=pipe, dscp=uniform, vxlan=disable]
-------------------------------- live log setup --------------------------------
08:39:25 init._fixture_func_decorator L0073 ERROR |
TypeError("'dict_keys' object is not subscriptable")
Traceback (most recent call last):
File "/data/tests/common/plugins/log_section_start/init.py", line 71, in _fixture_func_decorator
return fixture_func(*args, **kargs)
File "/data/tests/common/fixtures/fib_utils.py", line 304, in fib_info_files
fib_info = get_t2_fib_info(duthosts, duts_config_facts, duts_minigraph_facts)
File "/data/tests/common/fixtures/fib_utils.py", line 86, in get_t2_fib_info
if 'role' in ports[po_members[ifname].keys()[0]] and
TypeError: 'dict_keys' object is not subscriptable

Signed-off-by: yenlu <yenlu@cisco.com>