[T0 T1 merge] update multidut pfcwd tests
Summary: Update the missing T0 T1 tests feature in multidut

Fixes # (issue) 30929279

The following PR were migrated for pfcwd

- https://github.com/sonic-net/sonic-mgmt/pull/7370

- https://github.com/sonic-net/sonic-mgmt/pull/9567

- https://github.com/sonic-net/sonic-mgmt/pull/7367 to multidut code

- https://github.com/sonic-net/sonic-mgmt/pull/7712

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411

### Approach
#### What is the motivation for this PR?

#### How did you do it?

#### How did you verify/test it?

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.py
```

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/logs/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_m2o_with_snappi.xml -
================== 4 passed, 7 warnings in 1235.72s (0:20:35) ==================
```

snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.py
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/logs/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_burst_storm_with_snappi.xml -
================== 2 passed, 5 warnings in 858.60s (0:14:18) ===================

```

snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py (known failure on T2, fail as expected)

```
SKIPPED [4] snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py:190: Reboot type fast is not supported on cisco-8000 switches
FAILED snappi_tests/multidut/pfcwd/test_multidut_pfcwd_basic_with_snappi.py::test_pfcwd_basic_multi_lossless_prio_restart_service[multidut_port_info0-True-swss]
===== 1 failed, 23 passed, 16 skipped, 27 warnings in 27779.49s (7:42:59) ======
```

snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.py
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/logs/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_a2a_with_snappi.xml -
================== 4 passed, 7 warnings in 1157.40s (0:19:17) ==================
```

snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.py
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
- generated xml file: /var/src/sonic-mgmt_vmsvc5-t2-8800-ixia_669de75fbbfea63e8b73b319/tests/logs/snappi_tests/multidut/pfcwd/test_multidut_pfcwd_runtime_traffic_with_snappi.xml -
================== 2 passed, 6 warnings in 1162.35s (0:19:22) ==================
```