Refine pr merge blocking logic, define whether a job is required by code (#6255)
* Refine pr merge blocking logic, define whether a job is required by code
* Remove multiasic assert continueOnError in run-test-template.yml

What is the motivation for this PR?
Currently, we have some required jobs for allowing merging a pull request, in https://github.com/sonic-net/sonic-mgmt/settings/branch_protection_rules/14689274
But it's implicit and requires an admin auth to modify.
So I refined the logic, now we can define whether a job is required by continueOnError: false/true.
continueOnError: false means it's a required test job and will block merge if it fails
continueOnError: true means it's an optional test job and will not block merge even though it fails(unless a required test job depends on its result)

How did you do it?
Refine assert logic and project setting.

Co-authorized by jianquanye@microsoft.com