[drop_packet]: Change to run test case without error when loganalyzer is disabled (#7742)
What is the motivation for this PR?
When running drop_packets test case with --disable_loganalyzer, we see failure as below:

2023-03-14T16:09:50.4906997Z >       loganalyzer[enum_rand_one_per_hwsku_frontend_hostname].expect_regex = [LOG_EXPECT_PORT_OPER_DOWN_RE.format(rif_member_iface)]
2023-03-14T16:09:50.4907659Z E       TypeError: 'NoneType' object has no attribute '__getitem__'
Due to this, test case does not proceed to run.

How did you do it?
Create loganalyzer instance for specific dut within each fixture.

Signed-off-by: yenlu <yenlu@cisco.com>