[Python3 migration]Fix test failure caused by set_do_not_care_packet/set_do_not_care_scapy (#8113)
Fixes #8003 Getting AttributeError: Mask instance has no attribute 'set_do_not_care_packet' error while running acl test suite

What is the motivation for this PR?
In python2, ptf version is 0.9.1.
In python3, ptf version is 0.9.3.
Bound method set_do_not_care_packet for a Mask object is only available in ptf 0.9.3.

How did you do it?
Change set_do_not_care_packet back to set_do_not_care_scapy
New 0.9.3 code, set_do_not_care_scapy is a warpper of set_do_not_care_packet for compatibility.

How did you verify/test it?
Manually run tests/test_acl.py

Signed-off-by: yenlu <yenlu@cisco.com>