Update fwutil test_fwutil_install_bad_path case regex (#21410) (#22027)
Update fwutil test_fwutil_install_bad_path case regex to make it compatible for the new output in Debian 13

What is the motivation for this PR?
After SONiC base Debian upgrade to Debian 13, the output during execute the fwutil command for a bad package had been updated, just like that:

fwutil install chassis component BIOS fw BAD.pkg

Usage: fwutil install chassis component <component_name> fw
           [OPTIONS] <fw_path>
Try 'fwutil install chassis component <component_name> fw --help' for help.
Error: Invalid value for '<fw_path>': Path 'BAD.pkg' does not exist.

How did you do it?
Update the regex in the script to make the test compatible for the new changes.

How did you verify/test it?
Run it locally

Co-authored-by: Chuan Wu <103085864+echuawu@users.noreply.github.com>