Fix dualtor inventory parse error (#9482)
Approach
What is the motivation for this PR?
Fix the error:

inv_files = request.config.option.ansible_inventory
> ip = utilities.get_test_server_vars(inv_files, server).get('ansible_host')
E AttributeError: 'NoneType' object has no attribute 'get'
Signed-off-by: Longxiang Lyu lolv@microsoft.com

How did you do it?
The reason is that request.config.option.ansible_inventory returns a string, which could be a string of multiple inventory files like "inv_file0,inv_file1"

But InventoryManager takes inventory files as a list(https://github.com/ansible/ansible/blob/ca08261f08a5071cc5f8c73e61342f5a9581b9cd/lib/ansible/inventory/manager.py#L157-L163), so we should split the string if it contains multiple inventory files(from "inv_file0,inv_file1" to ["inv_file0", "inv_file1"]

How did you verify/test it?
Run pretests.