Convert ip_address to unicode (#4964)
Approach
What is the motivation for this PR?
For recent test_mac_move failures:
```
gaierror: [Errno -9] Address family for hostname not supported
This is because if we pass ipv4 address of string type to is_ipv4_address, it will return False.
```

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

How did you do it?
Convert the input to unicode before the check

How did you verify/test it?
Run test_mac_move