Fix TypeError when assertion message is not string
In python3 environment, current pytest version is 7.4.0. Comparing
with old pytest version in python2 environment, this pytest version
expect string type message argument passed to the pytest.fail function.

Some tests scripts may pass non-string error message to the pytest_assert
function which calls pytest.fail under the hood. In this case, pytest
will throw exception TypeError.

Example traceback:

        pytest.fail(message)
    File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 198, in fail
        raise Failed(msg=reason, pytrace=pytrace)
    File "/usr/local/lib/python3.8/dist-packages/_pytest/outcomes.py", line 38, in __init__
        raise TypeError(error_msg.format(type(self).__name__, type(msg).__name__))
    TypeError: Failed expected string as 'msg' parameter, got 'defaultdict' instead.

This patch fixes the issue by converting the non-string type message
passed in by test scripts to string type.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>