Fix import issue in wan/isis/test_authentication.py (#7684)
Script wan/isis/test_authentication.py tries to import a function like below:
```
from conftest import get_dut_port_p2p
```

This caused issue when we try to run pretests in run_tests.sh:
ImportError while importing test module '/azp/_work/23/s/tests/wan/isis/test_isis_authentication.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
wan/isis/test_isis_authentication.py:12: in <module>
    from conftest import get_dut_port_p2p
E   ImportError: cannot import name get_dut_port_p2p

Since function get_dut_port_p2p is only used by this script,
moved its definition from wan/isis/conftest into the script
itself to unblock other tests.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>