Fixed dut_basic_facts ansible module to have support SONiC images which does not have attribute "is_supervisor" (#6118)
Description of PR
Fixed dut_basic_facts ansible module to have support SONiC images which does not have attribute "is_supervisor"

Previoulsy when we call dut_basic_facts ansible module on SONiC image which does not have attribute "is_supervisor"(for example: 202012) we received error: AttributeError("'module' object has no attribute 'is_supervisor'"
Now issue fixed - script will work on all SONiC branches
Issue introduced in PR: #5708

Summary: Fixed dut_basic_facts ansible module to have support SONiC images which does not have attribute "is_supervisor"

What is the motivation for this PR?
Fix AttributeError("'module' object has no attribute 'is_supervisor'"

How did you do it?
See code

How did you verify/test it?
Executed ansible module: dut_basic_facts

Signed-off-by: Petro Pikh <petrop@nvidia.com>