Upgrade flask to fix the issue of starting mux simulator (#5202)
What is the motivation for this PR?
Recently we observed that starting mux simulator failed with error like below:

azure@server:~$ sudo python /home/azure/veos-vm/mux_simulator.py 8080 vms24-7 -v
Traceback (most recent call last):
File "/home/azure/veos-vm/mux_simulator.py", line 18, in
from flask import Flask, request, abort
File "/usr/local/lib/python3.8/dist-packages/flask/init.py", line 19, in
from . import json
File "/usr/local/lib/python3.8/dist-packages/flask/json/init.py", line 15, in
from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/init.py)

While deploying dualtor testbed, we always tried to install Flask version 1.1.2 on test server. Flask specified one
of dependant package "itsdangerous" as:

itsdangerous>=0.24
This means that the latest version of "itsdangerous" is always installed after "pip install Flask==1.1.2".

Recently the latest "itsdangerous" version deprecated something and caused this issue. It has been fixed in
Flask 2.0.0: https://itsdangerous.palletsprojects.com/en/2.1.x/changes

This article described the detailed reason and solutions:
https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/

How did you do it?
This PR updated the deployment code to use Flask 2.0.3 (current latest Flask version on pypi) which has the fix.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>