update ARP/dynamic_acl port selection for isolated topo. (#20533)
Description of PR
Summary:
Fixes the following error

arp/test_arp_extended.py::test_arp_garp_enabled[str5-7060x6-moby-512-1-None] 
-------------------------------- live log call ---------------------------------
01/09/2025 12:00:22 __init__.pytest_runtest_call             L0040 ERROR  | Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.8/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/var/src/sonic-mgmt_vms91-t0-7060x6-moby-512-1/tests/arp/test_arp_extended.py", line 52, in test_arp_garp_enabled
    pytest_assert(switch_arptable['arptable']['v4'][arp_request_ip]['macaddress'].lower() == arp_src_mac.lower())
KeyError: '192.168.0.4'
Current ARP related test cases uses the full port range for t0-isolated topo. While for Moby platform, the downstream port starts from Ethernet128, hence causing this error. Fix the port selected for all isolated topo in general.

Type of change
 Bug fix
 Testbed and Framework(new/improvement)
 New Test case
 Skipped for non-supported platforms
 Test case improvement

Approach
What is the motivation for this PR?
Fix the error for Moby isolated topo.

How did you do it?
use correct downstream ports for ARP related.

How did you verify/test it?
Verified on physical testbed

signed-off-by: jianquanye@microsoft.com