Added ignoring expected errors in test_add_rack TC (#6038)
What is the motivation for this PR?
There are scenarios, where TC applies patch by using config_updater, but updating is still considered as failed:
```
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: After applying patch to config, there are still some parts not updated
```
Steps from generic_patch.py module cover this case, but TC still failed due to errors of sonic_yang in syslog. So was added fixture which provides an approach for ignoring those errors.

How did you do it?
Added fixture which provides an approach for ignoring expected error messages of syslog in test_add_rack TC.

How did you verify/test it?
Run test cases. Tests passed.

configlet/test_add_rack.py::test_add_rack PASSED                                                                [100%]

Signed-off-by: Oleksandr Kozodoi <oleksandrx.kozodoi@intel.com>