fix issue 3666  Dict object has no attribute 'mgmtip' and 'HwSku' in resume_fanout_ports.yml (#3681)
What is the motivation for this PR?
Fix issue: #3666

How did you do it?
In resume_fanout_ports.yml, change

- set_fact:
    peer_host: "{{device_info['mgmtip']}}"
    peer_hwsku: "{{device_info['HwSku']}}"
to :

- set_fact:
    peer_host: "{{device_info[peer_device]['mgmtip']}}"
   peer_hwsku: "{{device_info[peer_device]['HwSku']}}"

How did you verify/test it?
Make some interfaces shutdown on DUT
Run ansible test case: warm_reboot_multi_sad_inboot.yaml
Check peer_host and peer_hwsku is set correctly by searching "resume_fanout_ports.yml:15" in test log