Fix no '_loader' attribute issue of cached variable manager (#2900)
Due the limitation of pickle, the variable manager objected loaded from pickle file does not
have the _loader and _hostvars attribute set. This could cause below exception when trying
to get host visible variables from cached variable manager:
    AttributeError: 'VariableManager' object has no attribute '_loader'
The cached inventory manager also has the similar issue.

The fix is not to cache inventory manager and variable manager. This PR also replaced pickle
with cPickle which is faster.

Signed-off-by: Xin Wang <xiwang5@microsoft.com>