[sonic-mgmt] Fix "fdb/test_fdb_mac_move.py" AttributeError failure
Test is relying on duthost method "get_crm_resources" method (parses
info from "crm show resources all" output)  to get "fdb_entry" crm
resource values. If output is empty for some reason then
"duthost.get_crm_resources().get("main_resources")" will be empty and thus
lead to "AttributeError: 'NoneType' object has no attribute 'get' during
get_crm_resources()" failure if we try to access "fdb_entry" key.

PR#11127 has introduced retry mechanism in case of empty output but condition is
incorrect ("len(duthost.get_crm_resources())") will never be 0. Correcting this
PR change to check for "main_resources" fixes the issue.