Skipping Everflow Policer test on Cisco 8223 platform (#23798)
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit
easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should
reviewer start? background context?
- List any dependencies that are required for this change.
-->
Skipping Everflow's policer testcase on Cisco 8223 platform ->
x86_64-8223_64e_mo-r0 and x86_64-8223_64ef_mo-r0 as policing is not
supported.

Testcase ->
everflow/test_everflow_testbed.py::TestEverflowV4IngressAclIngressMirror::test_everflow_dscp_with_policer

Failure seen ->

```
 @summary: Run EVERFLOW Policer Test
          ----------------------------------------------------------------------
           Traceback (most recent call last):
            File "/root/acstests/everflow_policer_test.py", line 365, in runTest
              assert rx_pps >= self.min_rx_pps and rx_pps <= self.max_rx_pps, assert_str
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
          AssertionError: min(90.0) <= pps(1739.6) <= max(110.00000000000001)

          ----------------------------------------------------------------------
          Ran 1 test in 57.779s

          FAILED (failures=1)
```
Summary:
Fixes # (issue)

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [x] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [ ] 202505
- [x] 202511

### Approach
#### What is the motivation for this PR?
Skipping Everflow's policer testcase on Cisco 8223 platform ->
x86_64-8223_64e_mo-r0 and x86_64-8223_64ef_mo-r0 as policing is not
supported on these platforms.

#### How did you do it?
Updated
sonic-mgmt/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml
to skip the test on unsupported platforms.

#### How did you verify/test it?
Ran the test with skip enabled and confirmed that the test is skipped on
these platforms - x86_64-8223_64e_mo-r0 and x86_64-8223_64ef_mo-r0

Failure Logs -
[policer_fail_logs.txt](https://github.com/user-attachments/files/26614825/policer_logs.1.txt)
Skip Logs -
[policer_skip_logs.txt](https://github.com/user-attachments/files/26614829/policer_skip_logs.1.txt)

#### Any platform specific information?
Test is being skipped for Cisco 8223 platform

#### Supported testbed topology if it's a new test case?
NA
### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->

Signed-off-by: Manasa Mananjaya <mmananja@cisco.com>
Signed-off-by: selldinesh <dinesh.sellappan@keysight.com>