Fix exception that partiallySucceeded build result not found (#6197)
* Fix exception that partiallySucceeded build result not found

Approach
What is the motivation for this PR?
If the partiallySucceeded or succeeded build result not found, getBuild will raise exception:
Traceback (most recent call last):
File "sonic-mgmt/tests/scripts/getbuild.py", line 146, in
main()
File "sonic-mgmt/tests/scripts/getbuild.py", line 134, in main
buildid_partial = find_latest_build_id(args.branch, "partiallySucceeded")
File "sonic-mgmt/tests/scripts/getbuild.py", line 110, in find_latest_build_id
latest_build_id = int(j['value'][0]['id'])
IndexError: list index out of range

This PR refine the logic to only require one result from partiallySucceeded or succeeded build result.

How did you do it?
Tolerate build id not found in function: find_latest_build_id

How did you verify/test it?
TestbedV2 t1-lag pipeline will go through this step.

Signed-off-by: Jianquan Ye<jianquanye@microsoft.com>