Improve the error message when non-exist testbed name is provided to run_tests.sh (#4770)
The error message of run_tests.sh is confusing if:
* non-exist testbed name is provided
* Yaml format testbed file is used.

For example:
```
$ ./run_tests.sh -i veos_vtb -n 'vms-kvm-xxx' -c ./dhcp_relay/test_dhcp_relay.py -f vtestbed.yaml
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
DUT name (-d) is not set..
Usage ./run_tests.sh [options]
    options with (*) must be provided
    -h -?          : get this help
    ...
```
This change added checking of existence of testbed name and improved
the error message

Signed-off-by: Xin Wang <xiwang5@microsoft.com>