Merged PR 366: Revert "Fix the test report summary issue which doesn't have the xfails info...
Revert "Fix the test report summary issue which doesn't have the xfails info (#5033)"

This reverts commit 5671856213940e21e64e933f8574b65eb0d0fc0a.

Public PR : https://github.com/Azure/sonic-mgmt/pull/5033

Errors seen while uploading results:
https://dev.azure.com/mssonic/internal/_build/results?buildId=68863&view=logs&j=bed026c5-b179-58e8-339f-77f4b7309744&t=7a119eb0-3078-59de-9dcc-52c41e36f1b7
```
+ python3 junit_xml_parser.py -d ../results -o tr.json
could not parse ../results/tests/logs/span/test_port_mirroring.xml: xfails not found in <testsuite> element - skipping
could not parse ../results/tests/logs/snappi/ecn/test_red_accuracy_with_snappi.xml: xfails not found in <testsuite> element - skipping
could not parse ../results/tests/logs/drop_packets/test_drop_counters.xml: xfails not found in <testsuite> element - skipping

Traceback (most recent call last):
  File "report_uploader.py", line 78, in <module>
    _run_script()
  File "report_uploader.py", line 48, in _run_script
    roots = validate_junit_xml_path(path_name)
  File "/azp/agent/_work/5/s/test_reporting/junit_xml_parser.py", line 210, in validate_junit_xml_path
    roots = validate_junit_xml_archive(path, strict)
  File "/azp/agent/_work/5/s/test_reporting/junit_xml_parser.py", line 201, in validate_junit_xml_archive
    raise JUnitXMLValidationError(f"provided directory {directory_name} does not contain any valid XML files")
junit_xml_parser.JUnitXMLValidationError: provided directory ../results does not contain any valid XML files

```