Added multi-asic support missing in PR #19170 (#20078)
A change in test_common/platform/interface_utils.py (get_physical_port_indices)
is causing all testcases in platform_tests/api/test_sfp.py::TestSfpApi to error out with the message:
TypeError: '<' not supported between instances of 'NoneType' and 'int'